name = "FF5Regression"
uuid = "f1a6dea7-d86f-40c0-8653-6b6c149737bb"
authors = ["krisha <krisha.doshi1@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
